/**
 * Cloudflare Workers entry point (wrangler.jsonc → "main").
 *
 * - fetch():     the unmodified OpenNext handler generated in .open-next/worker.js
 *                (plus installPrecompiledWasm() for the PDF renderer, see ./wasm.ts)
 * - scheduled(): Cron Trigger → calls the existing, bearer-protected cron route in-process
 *                (no public network hop), exactly like the external scheduler did on Netlify:
 *                  GET /api/cron/mapon   Authorization: Bearer $CRON_SECRET
 *
 * Skipped (with a log line) when CRON_SECRET is not set, so a fresh deployment without
 * secrets never produces failing cron runs. See docs/CLOUDFLARE_MIGRATION.md → "Cron".
 *
 * The cloudflare/ directory is excluded from the Next.js type-check (tsconfig.json):
 * it is Workers-only code and .open-next/worker.js only exists after `opennextjs-cloudflare build`.
 */
// @ts-expect-error -- generated by `opennextjs-cloudflare build` (resolved by wrangler)
import { default as handler } from "../.open-next/worker.js";
import { installPrecompiledWasm } from "./wasm";

// Training-material PDFs (@react-pdf/renderer → Yoga) need a precompiled WebAssembly module.
installPrecompiledWasm();

type Env = { CRON_SECRET?: string; [key: string]: unknown };
type Ctx = { waitUntil(promise: Promise<unknown>): void; passThroughOnException(): void };
type ScheduledController = { cron: string; scheduledTime: number };

/** Cron expression (wrangler.jsonc → triggers.crons) → internal route it calls. */
const CRON_ROUTES: Record<string, string> = {
  "*/10 * * * *": "/api/cron/mapon",
  // Optional daily tender refresh — add "17 5 * * *" to triggers.crons to enable:
  "17 5 * * *": "/api/cron/tenders",
};

// Only used to build an absolute Request URL; the request never leaves the isolate.
const INTERNAL_ORIGIN = "https://mjforestguru.com";

async function runCron(path: string, env: Env, ctx: Ctx) {
  const secret = typeof env.CRON_SECRET === "string" ? env.CRON_SECRET : "";
  if (!secret) {
    console.warn(`[cron] ${path} skipped: CRON_SECRET is not set`);
    return;
  }
  const started = Date.now();
  const res: Response = await handler.fetch(
    new Request(new URL(path, INTERNAL_ORIGIN), {
      method: "GET",
      headers: { authorization: `Bearer ${secret}`, "user-agent": "cloudflare-cron" },
    }),
    env,
    ctx,
  );
  const body = (await res.text()).slice(0, 500);
  const line = `[cron] ${path} → ${res.status} in ${Date.now() - started} ms ${body}`;
  // A non-2xx status marks the invocation as failed in Workers observability.
  if (!res.ok) throw new Error(line);
  console.log(line);
}

const worker = {
  fetch: handler.fetch,
  async scheduled(controller: ScheduledController, env: Env, ctx: Ctx) {
    const path = CRON_ROUTES[controller.cron];
    if (!path) {
      console.warn(`[cron] no route mapped for "${controller.cron}"`);
      return;
    }
    await runCron(path, env, ctx);
  },
};

export default worker;
