/**
 * Cloudflare Workers build preparation (run with tsx; NOT used by the Netlify build).
 *
 * Invoked by `npm run build:cf-next`, which open-next.config.ts sets as the build command,
 * so a plain `npx opennextjs-cloudflare build` runs it automatically before `npm run build`.
 * Everything it writes is git-ignored and regenerated on every build:
 *
 *  1. cloudflare/.generated/yoga.wasm (+ yoga-meta.js)
 *       Yoga's WebAssembly, extracted byte-for-byte from the base64 string inside
 *       node_modules/yoga-layout, so wrangler can upload it as a precompiled module
 *       (Workers cannot compile WebAssembly from bytes at runtime). See cloudflare/wasm.ts.
 *  2. public/pdf-fonts/*.ttf
 *       The training-PDF fonts (src/lib/training/pdf/fonts). On Workers there is no file
 *       system, so the PDF renderer fetches them as static assets instead of reading disk.
 *  3. public/_headers
 *       Workers static assets are served without running Next.js, so the headers that
 *       next.config.ts sets (CSP, HSTS, X-Frame-Options, cache rules for /sw.js, /maplibre,
 *       /geo) would be missing on them. They are generated from next.config.ts itself, so
 *       the two never drift. Requires the same NEXT_PUBLIC_SUPABASE_URL as the build.
 */
import { createHash } from "node:crypto";
import { copyFileSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = process.cwd();

/* ---------------------------------------------------------------- 1. yoga.wasm */
{
  const src = join(root, "node_modules/yoga-layout/dist/binaries/yoga-wasm-base64-esm.js");
  const js = readFileSync(src, "utf8");
  const m = js.match(/data:application\/octet-stream;base64,([A-Za-z0-9+/=]+)/);
  if (!m) throw new Error(`[cf-prepare] could not find the embedded wasm in ${src} (yoga-layout changed?)`);
  const wasm = Buffer.from(m[1], "base64");
  if (wasm.subarray(0, 4).toString("hex") !== "0061736d") throw new Error("[cf-prepare] extracted yoga binary is not WebAssembly");
  const out = join(root, "cloudflare/.generated");
  mkdirSync(out, { recursive: true });
  writeFileSync(join(out, "yoga.wasm"), wasm);
  const sha = createHash("sha256").update(wasm).digest("hex");
  writeFileSync(
    join(out, "yoga-meta.js"),
    `// generated by scripts/cloudflare/prepare.ts — do not edit\nexport const YOGA_WASM_BYTES = ${wasm.length};\nexport const YOGA_WASM_SHA256 = "${sha}";\n`,
  );
  console.log(`[cf-prepare] yoga.wasm ${wasm.length} bytes sha256=${sha.slice(0, 12)}…`);
}

/* ---------------------------------------------------------------- 2. PDF fonts */
{
  const src = join(root, "src/lib/training/pdf/fonts");
  const out = join(root, "public/pdf-fonts");
  mkdirSync(out, { recursive: true });
  const files = readdirSync(src).filter((f) => f.endsWith(".ttf") || f.endsWith(".txt"));
  for (const f of files) copyFileSync(join(src, f), join(out, f));
  console.log(`[cf-prepare] ${files.length} PDF font/licence files → public/pdf-fonts`);
}

/* ---------------------------------------------------------------- 3. _headers */
async function writeHeaders() {
  // Same module Next.js loads, evaluated with the same environment (NODE_ENV=production
  // makes it emit the production CSP without 'unsafe-eval' / localhost sources).
  (process.env as Record<string, string>).NODE_ENV = "production";
  const { default: nextConfig } = await import("../../next.config");
  const rules = (await nextConfig.headers?.()) ?? [];
  const lines: string[] = [
    "# generated by scripts/cloudflare/prepare.ts from next.config.ts — do not edit",
    "# Applies to Workers static assets only; dynamic responses get headers from Next.js.",
  ];
  const toPattern = (source: string) => source.replace(/\/:path\*$/, "/*").replace(/:path\*/g, "*");
  for (const rule of rules) {
    lines.push(toPattern(rule.source));
    for (const h of rule.headers) {
      if (h.value.length > 2000) throw new Error(`[cf-prepare] header ${h.key} is longer than the 2000-character _headers limit`);
      lines.push(`  ${h.key}: ${h.value}`);
    }
  }
  // Hashed build output never changes under the same URL.
  lines.push("/_next/static/*", "  Cache-Control: public, max-age=31536000, immutable");
  writeFileSync(join(root, "public/_headers"), lines.join("\n") + "\n");
  console.log(`[cf-prepare] public/_headers: ${rules.length + 1} rules`);
  if (!process.env.NEXT_PUBLIC_SUPABASE_URL) console.warn("[cf-prepare] NEXT_PUBLIC_SUPABASE_URL is not set: the CSP will not allow Supabase");
}

writeHeaders().catch((e) => {
  console.error(e);
  process.exit(1);
});
